version: '3'

services:
  frontend:
    build:
      context: ./dearburgerFE
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./dearburgerBE
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=codeigniter_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: codeigniter_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
